Day 26: How do I find and remove duplicate rows in pandas?

In [1]:
import pandas as pd

In [9]:
# read a  dataset of movies reviewers (modifying the default parameter values for read_table)
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table("https://bit.ly/movieusers", sep="|", header=None, names=user_cols, index_col='user_id')

In [10]:
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [11]:
users.shape

(943, 4)

Now, if you want to identify duplicate zip codes.
You can use a series method

In [13]:
users.zip_code.duplicated().sum() # Returns true if there is an entry previous to it with the same value, i.e. above it. Using the sum method, the true get converted to 1 and false get converted to 0. This implies that there are 148 duplicate zip codes.

148

For checking duplication in the data frame as a whole instead of series.

In [15]:
users.duplicated().sum() # This will output true, if the entire row, is duplicate or is present before it.

7

In order to see the duplicate rows, we can use the loc method.

In [17]:
users.loc[users.duplicated(keep='first'), : ] # We can pass in series of boolean where the value is true, Mark duplicate as true, except the first occurrence of the row, so here the first occurrence is kept and rest of the remaining once are identified as duplicates.
#users.loc[users.duplicated(keep='last'), : ]

         age gender occupation zip_code
user_id
496       21      F    student    55414
572       51      M   educator    20003
621       17      M    student    60402
684       28      M    student    55414
733       44      F      other    60630
805       27      F      other    20009
890       32      M    student    97301

For dropping the duplicates use the following method.

In [20]:
users.drop_duplicates(keep='last').shape # keep='last' and keep='first' return the same result. This will not occur inplace by default.

(936, 4)

In [21]:
users.drop_duplicates(keep=False).shape # This will drop all the row that are tagged as duplicate i.e. both the entries first 7 and last 7

(929, 4)

If you want to consider certain columns when considering duplicates. When identifying duplicates. Example: if you want to keep age+zip code as a unique identifier.

In [25]:
users.duplicated(subset=['age', 'zip_code']).shape# This implies that if you are considering age and zip code, then there are 16 elements.

(943,)

In [23]:
# For dropping the duplicate rows 
users.drop_duplicates(subset=['age', 'zip_code']).shape

(927, 4)